name: CI/CD

on:
  push:
    branches:
      - 'develop'
      - 'main'

jobs:
  prepare_env:
    runs-on: ubuntu-latest
    outputs:
      repo_name: ${{ steps.tratar_name.outputs.repo_name }}
    steps:
      - name: Tratar Name
        id: tratar_name
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d/ -f2 | tr '[:upper:]' '[:lower:]')
          echo "ðŸ§© Nome do repo: $REPO_NAME"
          echo "repo_name=$REPO_NAME" >> $GITHUB_OUTPUT
  build-and-push:
    runs-on: ubuntu-latest
    needs: prepare_env
    env:
      REPO_NAME: ${{ needs.prepare_env.outputs.repo_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image tag and AWS variables
        id: vars
        run: |
          AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          AWS_REGION=sa-east-1
          TAG=dev-$(date +%s)
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID" >> $GITHUB_ENV
          echo "AWS_REGION=$AWS_REGION" >> $GITHUB_ENV

      - name: Build and Push Image
        run: |
          IMAGE=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME:$TAG
          docker build -t $IMAGE -f Dockerfile .
          docker push $IMAGE
          echo "IMAGE_URI=$IMAGE" >> $GITHUB_ENV
      - name: Update image in platform-configs
        uses: actions/checkout@v4
        with:
          repository: officialmutualbank/platform-configs
          path: platform-configs
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Patch frontend deployment
        run: |
          sed -i "s|image: .*|image: $IMAGE_URI|" platform-configs/repo-configs/$REPO_NAME/hml/deployment.yaml
      - name: Commit and push
        run: |
          cd platform-configs
          git config user.name "github-actions"
          git config user.email "ci@github.com"
          git add .
          git commit -m "chore: update frontend image to $IMAGE_URI"
          git push
